# Stage 1: Install dependencies and build the application
FROM node:22.2-alpine AS builder
WORKDIR /app

# Copy package files and install dependencies
# (Install only production and development dependencies for building)
COPY package.json package-lock.json ./
RUN npm ci 
# --only=production

# Copy the rest of the source code
COPY . .

# Build the Next.js application
RUN npm run build

# Remove devDependencies after build
RUN npm prune --production

# Stage 2: Create the production image
FROM node:22.2-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy necessary files from builder stage
# (Copy the build output, public assets, and node_modules)
COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

# Expose the port (Next.js)
EXPOSE 3000

# Start the Next.js server
CMD ["node_modules/.bin/next", "start", "-H", "0.0.0.0"]

